#!/bin/bash
# Weave — WSL/Linux Installer
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/leandro-br-dev/weave/main/install.sh | bash
#   or: bash install.sh  (from inside the cloned repo)
set -e

GREEN='\033[0;32m' RED='\033[0;31m' YELLOW='\033[1;33m' CYAN='\033[0;36m' NC='\033[0m'
ok()   { echo -e "${GREEN}  ✓ $*${NC}"; }
err()  { echo -e "${RED}  ✗ $*${NC}"; }
warn() { echo -e "${YELLOW}  ⚠ $*${NC}"; }
info() { echo -e "${CYAN}  → $*${NC}"; }

ask() {
  local prompt="$1" var="$2" default="$3"
  printf '%s' "$prompt"
  if [ -t 0 ]; then
    read -r "$var"
  else
    read -r "$var" < /dev/tty
  fi
  eval "[ -z \"\$$var\" ] && $var=\"$default\""
}

REPO_URL='https://github.com/leandro-br-dev/weave.git'

echo ''
echo '████████████████████████████████████████'
echo '  Weave — Installer'
echo '████████████████████████████████████████'
echo ''

# ─── Check dependencies ───────────────────────────────────────
echo '→ Checking dependencies...'
MISSING=0

check_dep() {
  local cmd=$1 name=$2 install_hint=$3
  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$name found: $($cmd --version 2>&1 | head -1)"
  else
    err "$name NOT found"
    warn "Install: $install_hint"
    MISSING=$((MISSING + 1))
  fi
}

check_dep git     'Git'     'sudo apt install git'
check_dep node    'Node.js' 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt install -y nodejs'
check_dep python3 'Python3' 'sudo apt install python3 python3-pip python3-venv'
check_dep curl    'curl'    'sudo apt install curl'

if command -v claude >/dev/null 2>&1; then
  ok "Claude CLI found: $(claude --version 2>&1 | head -1)"
else
  warn 'Claude CLI not found (recommended)'
  warn 'Install: npm install -g @anthropic-ai/claude-code'
fi

if [ $MISSING -gt 0 ]; then
  echo ''
  err "$MISSING required dependency(ies) missing. Install them and re-run."
  exit 1
fi
echo ''

# ─── Detect install location ──────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-/dev/stdin}")" 2>/dev/null && pwd || echo '')"
IN_REPO=false
if [ -f "$SCRIPT_DIR/api/package.json" ] && [ -f "$SCRIPT_DIR/client/main.py" ]; then
  IN_REPO=true
fi

DEFAULT_INSTALL="$HOME/weave"
if [ "$IN_REPO" = true ]; then
  ask "Install location [$SCRIPT_DIR]: " INSTALL_DIR "$SCRIPT_DIR"
else
  ask "Install location [$DEFAULT_INSTALL]: " INSTALL_DIR "$DEFAULT_INSTALL"
fi
INSTALL_DIR="${INSTALL_DIR/#\~/$HOME}"
echo ''

# ─── Clone or reuse ───────────────────────────────────────────
if [ "$IN_REPO" = true ] && [ "$(realpath "$SCRIPT_DIR" 2>/dev/null)" = "$(realpath "$INSTALL_DIR" 2>/dev/null)" ]; then
  info "Using existing repository at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  git pull --quiet 2>/dev/null && ok 'Repository up to date' || ok 'Repository ready'
elif [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing installation at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  git pull --quiet && ok 'Updated to latest version'
else
  info "Cloning repository to $INSTALL_DIR..."
  git clone "$REPO_URL" "$INSTALL_DIR" --quiet
  ok "Cloned to $INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ─── Install dependencies ─────────────────────────────────────
info 'Installing API dependencies...'
cd api && npm install --silent && ok 'API dependencies installed' && cd ..

info 'Installing Dashboard dependencies...'
cd dashboard && npm install --silent && ok 'Dashboard dependencies installed' && cd ..

info 'Creating Python virtual environment...'
cd client
python3 -m venv venv
venv/bin/pip install -r requirements.txt -q
ok 'Python environment ready'
cd ..

# ─── Configure .env ───────────────────────────────────────────
CURRENT_TOKEN=""
[ -f .env ] && CURRENT_TOKEN=$(grep '^WEAVE_TOKEN=' .env 2>/dev/null | cut -d= -f2 | tr -d '[:space:]' || echo '')

sync_token() {
  local token=$1

  cat > dashboard/.env << EOF
VITE_API_URL=http://localhost:3000
VITE_API_TOKEN=$token
EOF

  cat > api/.env << EOF
PORT=3000
API_BEARER_TOKEN=$token
WEAVE_TOKEN=$token
EOF

  ok 'Token synced to dashboard/.env and api/.env'
}

if [ ! -f .env ] || [ "$CURRENT_TOKEN" = "dev-token-change-in-production" ] || [ -z "$CURRENT_TOKEN" ]; then
  info 'Generating secure .env configuration...'
  TOKEN=$(python3 -c 'import secrets; print(secrets.token_hex(24))')
  cat > .env << EOF
# Weave Configuration — generated by installer
WEAVE_TOKEN=$TOKEN
PORT=3000
DASHBOARD_PORT=5173
APPROVAL_TIMEOUT_MINUTES=10
# APP_ENV=dev  ← uncomment to run as development instance (ports +100)
EOF
  ok ".env created with secure token: ${TOKEN:0:8}..."
  sync_token "$TOKEN"
else
  ok ".env already configured (token: ${CURRENT_TOKEN:0:8}...)"
  sync_token "$CURRENT_TOKEN"
fi

mkdir -p "$HOME/.local/share/weave"
# projects/ and other subdirs will be created by start.sh
ok 'Data directory ready'

# ─── Desktop shortcut ─────────────────────────────────────────
echo ''
ask 'Create desktop shortcut? [Y/n] ' CREATE_SHORTCUT 'y'

if [ "${CREATE_SHORTCUT,,}" != 'n' ]; then

  IS_WSL=false
  grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=true

  if [ "$IS_WSL" = true ]; then

    # Detect WSL distro name — strip null bytes
    WSL_DISTRO=$(grep '^NAME=' /etc/os-release 2>/dev/null | cut -d'"' -f2 | tr -d '\0\r\n' | head -1 || echo '')
    if [ -z "$WSL_DISTRO" ]; then
      WSL_DISTRO=$(cat /etc/os-release 2>/dev/null | grep '^ID=' | cut -d= -f2 | tr -d '"' || echo 'ubuntu')
    fi

    # Use PowerShell to create a proper .lnk shortcut
    # This is more reliable than creating a .bat and avoids path detection issues
    if command -v powershell.exe >/dev/null 2>&1; then
      info 'Creating Windows desktop shortcut via PowerShell...'

      # Escape the install dir for use inside PowerShell string
      PS_INSTALL_DIR=$(echo "$INSTALL_DIR" | sed "s/'/\\'\\'/g")

      PS_OUTPUT=$(powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
\$ErrorActionPreference = 'Stop'
try {
  \$desktop = [Environment]::GetFolderPath('Desktop')
  \$lnkPath = Join-Path \$desktop 'Weave (WSL).lnk'
  \$wshell = New-Object -ComObject WScript.Shell
  \$shortcut = \$wshell.CreateShortcut(\$lnkPath)
  \$shortcut.TargetPath = 'C:\Windows\System32\wsl.exe'
  \$shortcut.Arguments = '-d \"$WSL_DISTRO\" bash -c \"cd ''$PS_INSTALL_DIR'' && bash start.sh; exec bash\"'
  \$shortcut.Description = 'Weave'
  \$shortcut.WorkingDirectory = 'C:\Windows\System32'
  \$shortcut.Save()
  Write-Output \"OK: \$lnkPath\"
} catch {
  Write-Output \"FAIL: \$_\"
  exit 1
}
" 2>&1)

      # Check exit code from PowerShell
      PS_EXIT=$?
      PS_OUTPUT_CLEAN=$(echo "$PS_OUTPUT" | tr -d '\r\0')

      echo "$PS_OUTPUT_CLEAN" | while IFS= read -r line; do
        case "$line" in
          OK:*)   ok "Desktop shortcut created: ${line#OK: }" ;;
          FAIL:*) warn "Shortcut creation failed: ${line#FAIL: }" ;;
          *)      [ -n "$line" ] && echo "  $line" ;;
        esac
      done

      # If PowerShell exited with error and we got no OK line, report it
      if [ $PS_EXIT -ne 0 ] && ! echo "$PS_OUTPUT_CLEAN" | grep -q '^OK:'; then
        err "PowerShell exited with code $PS_EXIT"
      fi
    else
      warn 'powershell.exe not found — cannot create Windows shortcut automatically.'
      warn "Create manually: Right-click Desktop → New Shortcut"
      warn "  Target: wsl.exe -d \"$WSL_DISTRO\" bash -c \"cd '$INSTALL_DIR' && bash start.sh; exec bash\""
    fi
  fi

  # Linux application menu entry
  mkdir -p "$HOME/.local/share/applications"
  cat > "$HOME/.local/share/applications/weave.desktop" << EOF
[Desktop Entry]
Name=Weave
Comment=AI Agent Orchestration Platform
Exec=bash -c 'cd $INSTALL_DIR && bash start.sh; exec bash'
Terminal=true
Type=Application
Icon=utilities-terminal
Categories=Development;
EOF
  ok 'Application menu entry created'
fi

# ─── Done ─────────────────────────────────────────────────────
echo ''
echo '████████████████████████████████████████'
ok 'Weave installed successfully!'
echo ''
info "Start: cd $INSTALL_DIR && bash start.sh"
info 'Or use the desktop shortcut if created'
echo '████████████████████████████████████████'
echo ''